export const MAPS = [
  { id: 10875, name: "Arabia", icon: "arabia.png" },
  { id: 10876, name: "Archipelago", icon: "archipelago.png" },
  { id: 10877, name: "Baltic", icon: "baltic.png" },
  { id: 10878, name: "Black Forest", icon: "black_forest.png" },
  { id: 10879, name: "Coastal", icon: "coastal.png" },
  { id: 10880, name: "Continental", icon: "continental.png" },
  { id: 10881, name: "Crater Lake", icon: "crater_lake.png" },
  { id: 10882, name: "Fortress", icon: "fortress.png" },
  { id: 10883, name: "Gold Rush", icon: "gold_rush.png" },
  { id: 10884, name: "Highland", icon: "highland.png" },
  { id: 10885, name: "Islands", icon: "islands.png" },
  { id: 10886, name: "Mediterranean", icon: "mediterranean.png" },
  { id: 10887, name: "Migration", icon: "migration.png" },
  { id: 10888, name: "Rivers", icon: "rivers.png" },
  { id: 10889, name: "Team Islands", icon: "team_islands.png" },
  { id: 10891, name: "Scandinavia", icon: "scandinavia.png" },
  { id: 10892, name: "Mongolia", icon: "mongolia.png" },
  { id: 10894, name: "Yucatan", icon: "yucatan.png" },
  { id: 10893, name: "Salt Marsh", icon: "salt_marsh.png" },
  { id: 10895, name: "Arena", icon: "arena.png" },
  { id: 10897, name: "Oasis", icon: "oasis.png" },
  { id: 10898, name: "Ghost Lake", icon: "ghost_lake.png" },
  { id: 10901, name: "Nomad", icon: "nomad.png" },
  { id: 10914, name: "Acropolis", icon: "acropolis.png" },
  { id: 10915, name: "Budapest", icon: "budapest.png" },
  { id: 10916, name: "Cenotes", icon: "cenotes.png" },
  { id: 10917, name: "City of Lakes", icon: "city_of_lakes.png" },
  { id: 10918, name: "Golden Pit", icon: "golden_pit.png" },
  { id: 10919, name: "Hideout", icon: "hideout.png" },
  { id: 10920, name: "Hill Fort", icon: "hill_fort.png" },
  { id: 10921, name: "Lombardia", icon: "lombardia.png" },
  { id: 10922, name: "Steppe", icon: "steppe.png" },
  { id: 10923, name: "Valley", icon: "valley.png" },
  { id: 10924, name: "Megarandom", icon: "megarandom.png" },
  { id: 10925, name: "Hamburger", icon: "hamburger.png" },
  { id: 10930, name: "Golden Swamp", icon: "golden_swamp.png" },
  { id: 10931, name: "Four Lakes", icon: "four_lakes.png" },
  { id: 10932, name: "Land Nomad", icon: "land_nomad.png" },
  { id: 10933, name: "Battle on the Ice", icon: "battle_on_the_ice.png" },
  { id: 10934, name: "El Dorado", icon: "el_dorado.png" },
  { id: 10935, name: "Fall of Axum", icon: "fall_of_axum.png" },
  { id: 10936, name: "Fall of Rome", icon: "fall_of_rome.png" },
  { id: 10937, name: "The Majapahit Empire", icon: "the_majapahit_empire.png" },
  { id: 10938, name: "Amazon Tunnel", icon: "amazon_tunnel.png" },
  { id: 10939, name: "Coastal Forest", icon: "coastal_forest.png" },
  { id: 10940, name: "African Clearing", icon: "african_clearing.png" },
  { id: 10941, name: "Atacama", icon: "atacama.png" },
  { id: 10942, name: "Seize the Mountain", icon: "seize_the_mountain.png" },
  { id: 10943, name: "Crater", icon: "crater.png" },
  { id: 10944, name: "Crossroads", icon: "crossroads.png" },
  { id: 10945, name: "Michi", icon: "michi.png" },
  { id: 10947, name: "Volcanic Island", icon: "volcanic_island.png" },
  { id: 10948, name: "Acclivity", icon: "acclivity.png" },
  { id: 10949, name: "Eruption", icon: "eruption.png" },
  { id: 10950, name: "Frigid Lake", icon: "frigid_lake.png" },
  { id: 10951, name: "Greenland", icon: "greenland.png" },
  { id: 10952, name: "Lowland", icon: "lowland.png" },
  { id: 10953, name: "Marketplace", icon: "marketplace.png" },
  { id: 10954, name: "Meadow", icon: "meadow.png" },
  { id: 10955, name: "Mountain Range", icon: "mountain_range.png" },
  { id: 10956, name: "Northern Isles", icon: "northern_isles.png" },
  { id: 10957, name: "Ring Fortress", icon: "ring_fortress.png" },
  { id: 10958, name: "Runestones", icon: "runestones.png" },
  { id: 10959, name: "Aftermath", icon: "aftermath.png" },
  { id: 10960, name: "Enclosed", icon: "enclosed.png" },
  { id: 10961, name: "Haboob", icon: "haboob.png" },
  { id: 10962, name: "Kawasan", icon: "kawasan.png" },
  { id: 10963, name: "Land Madness", icon: "land_madness.png" },
  { id: 10964, name: "Sacred Springs", icon: "sacred_springs.png" },
  { id: 10965, name: "Wade", icon: "wade.png" },
  { id: 10966, name: "Morass", icon: "morass.png" },
  { id: 10967, name: "Shoals", icon: "shoals.png" },
  { id: 10968, name: "Cliffbound", icon: "cliffbound.png" },
  { id: 10969, name: "Isthmus", icon: "isthmus.png" },
  { id: 10970, name: "Dunesprings", icon: "dunesprings.png" },
  { id: 10971, name: "Golden Stream", icon: "golden_stream.png" },
  { id: 10972, name: "Mountain Dunes", icon: "mountain_dunes.png" },
  { id: 10973, name: "River Divide", icon: "river_divide.png" },
  { id: 10974, name: "Sandrift", icon: "sandrift.png" },
  { id: 10975, name: "Shrubland", icon: "shrubland.png" },
  { id: 10976, name: "Passage", icon: "passage.png" },
  { id: 10977, name: "Hollow Woodlands", icon: "hollow_woodlands.png" },
  { id: 10978, name: "Karsts", icon: "karsts.png" },
];

export const getMapById = (id: number) => MAPS.find((m) => m.id === id);
