ALTER TABLE DONATIONS
  DROP COLUMN IF EXISTS PAYMENT_INTENT_ID,
  DROP COLUMN IF EXISTS CHECKOUT_SESSION_ID;

ALTER TABLE DONATIONS
    ADD COLUMN IF NOT EXISTS PAY_ID TEXT UNIQUE,
    ADD COLUMN IF NOT EXISTS MERCHANT_PAYMENT_ID TEXT UNIQUE;

ALTER TABLE DONATIONS
ALTER COLUMN AMOUNT TYPE NUMERIC(10,2)
  USING AMOUNT::NUMERIC(10,2);

ALTER TABLE DONATIONS
ALTER COLUMN CURRENCY SET DEFAULT 'GEL';

ALTER TABLE DONATIONS
DROP CONSTRAINT IF EXISTS DONATIONS_STATUS_CHECK;

ALTER TABLE DONATIONS
    ADD CONSTRAINT DONATIONS_STATUS_CHECK
        CHECK (STATUS IN ('PENDING', 'PAID', 'FAILED', 'EXPIRED'));

ALTER TABLE DONATIONS
DROP CONSTRAINT IF EXISTS DONATIONS_CURRENCY_CHECK;

ALTER TABLE DONATIONS
    ADD CONSTRAINT DONATIONS_CURRENCY_CHECK
        CHECK (CURRENCY IN ('GEL', 'USD'));

ALTER TABLE DONATIONS
ALTER COLUMN CREATED_AT TYPE TIMESTAMPTZ
  USING CREATED_AT::TIMESTAMPTZ;
